### ISSUE TITLE
Sensor Units(5701) of generic sensor(3300) should be a string

### ISSUE THREAD

**Issue by sbernard31** [connectIOT/lwm2m-objects#2]
In the [xml](https://github.com/connectIOT/lwm2m-objects/blob/master/ipso/1.0/xml/3300.xml) this is a float, this does not respect the [spec](https://github.com/connectIOT/lwm2m-objects/blob/master/ipso/1.0/IPSO-Smart-Objects-1.0.pdf).

**Comment by mjkoster** [comment]
Yes, units should always be a string. Thanks for the note!

**Comment by mjkoster** [comment]
Posting this to the IPSO Github Issues

**Comment by mjkoster** [comment]
Posted to the issues at https://github.com/IPSO-Alliance/SmartObjectGuidelines/issues/9
closing here. Please use the IPSO Github for all smart object guideline and schema issues at:
https://github.com/IPSO-Alliance/SmartObjectGuidelines/issues

Thanks!
